# Generated by Django 6.0.6 on 2026-06-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Exalore ERP', max_length=255)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='company/header/')),
                ('footer_image', models.ImageField(blank=True, null=True, upload_to='company/footer/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
