# Generated by Django 6.0.6 on 2026-06-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_code",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
