# Generated by Django 6.0.6 on 2026-06-21 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_item_item_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemunit",
            name="is_purchase_unit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.itemgroup",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="itemgroup",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="itemprice",
            name="minimum_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="itemprice",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.unit"
            ),
        ),
        migrations.AlterField(
            model_name="itemunit",
            name="conversion_factor",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name="itemunit",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.unit"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="itemprice",
            unique_together={("item", "unit")},
        ),
        migrations.AlterUniqueTogether(
            name="itemunit",
            unique_together={("item", "unit")},
        ),
    ]
