# Generated by Django 6.0.6 on 2026-06-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_itemunit_is_purchase_unit_alter_item_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemunit",
            name="is_purchase_unit",
        ),
    ]
